version: '3.8'
services:
  sqlserver:
    container_name: sqlserver
    environment: 
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=myStrongPassword12#
    ports:
      - '1433:1433'
    volumes:
      - sqldata:/var/opt/mssql/sqlserver
    image: mcr.microsoft.com/mssql/server
  web-app:
    container_name: web-app
    image: softunibazar     # my image  
    build:
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - '80:80'
volumes:
  sqldata:
    external: true